class Envs:
    ENV_WAII_API_KEY = 'WAII_API_KEY'
    ENV_OPENAI_API_KEY = 'OPENAI_API_KEY'
    ENV_WAII_API_SERVER_URL = 'WAII_API_SERVER_URL'
    ENV_DATABASE_CONNECTION_KEY = 'DATABASE_CONNECTION_KEY'